systemd now handles starting i3, conky, compton, etc. Added my xinitrc and bash profile.

diff --git a/bin/sys b/bin/sys
--- a/bin/sys
+++ b/bin/sys
@@ -7,6 +7,11 @@ LIST=()
 AALL=
 AFAILED=
 AACTIVE=
+LOGSINCE=
+LOGLEVEL=
+LOGBOOTS=" -b "
+LOGTAIL=
+LOG=
 
 if [ -z "$1" ]; then
     LIST=( list-units )
@@ -35,7 +40,7 @@ usage:
     -S => start
     -K => stop
     -Q => status
-    -L => reload
+    -C => reload
 
     -0 => disable
     -1 => enable
@@ -47,6 +52,15 @@ usage:
     -x : show failed services
     -a : show all services (includes inactive)
     -! : show all units (not just services)
+    -t => list timers, works with 1, 0
+    
+    -L => logs (journalctl)
+    -. => tail aka follow (keep watching)
+    -e => loglevel error
+    -w => loglevel warning
+    -d => loglevel debug 
+    -b => all boots (defaults to just this boot)
+    -5 => only last 5 minutes
 EOF
             exit
             ;;
@@ -72,7 +86,7 @@ EOF
                     Q )
                         ACTION+=( status )
                         ;;
-                    L )
+                    C )
                         ACTION+=( reload )
                         ;;
                     0)
@@ -99,6 +113,30 @@ EOF
                     a ) 
                         AACTIVE=TRUE
                         ;;
+                    e ) 
+                        LOGLEVEL=3
+                        ;;
+                    w ) 
+                        LOGLEVEL=4
+                        ;;
+                    d ) 
+                        LOGLEVEL=7
+                        ;;
+                    5 )
+                        LOGSINCE='"5 minutes ago"'
+                        ;;
+                    b )
+                        LOGBOOTS=
+                        ;;
+                    L )
+                        LOG=TRUE
+                        ;;
+                    . )
+                        LOGTAIL=" -f "
+                        ;;
+                    t )
+                        TIMERS=TRUE
+                        ;;
                     * )
                         echo "bad arg: -$CHAR"
                         ;;
@@ -114,7 +152,10 @@ EOF
 done
 
 if [ -z "$USERMODE" -a -z "$GLOBALMODE" ]; then
-    if [ ${#ACTION[@]} -eq 1 ] && [ "${ACTION[0]}" == "status" ];then
+    if [ ${#ACTION[@]} -eq 1 ] && 
+       [ "${ACTION[0]}" == "status" ] && 
+       [ -z "DAEMON_RELOAD" ]; 
+    then
         CMD="systemctl"
     else
         CMD="sudo systemctl"
@@ -143,24 +184,75 @@ for cmd in ${LIST[@]}; do
 
     if [ -z "$UNITS" ]; then
         SYSTEMD_COLORS=1 $CMD $cmd $ARG | sed '/^$/q'  
-        
         Q="$($CMD $cmd $ARG --no-legend | cut -d' ' -f1)"
         UNITS+=( $Q )
     else
-        $CMD $cmd $ARG --no-legend | grep $UNITS
-        
-        Q="$($CMD $cmd $ARG --no-legend | grep $UNITS | cut -d' ' -f1)"
-        UNITS=( $Q )
+        U=()
+        for u in ${UNITS[@]}; do
+            $CMD $cmd $ARG --no-legend | grep $UNITS
+            Q="$($CMD $cmd $ARG --no-legend | grep $UNITS | cut -d' ' -f1)"
+            U+=( $Q )
+        done
+        UNITS=$U
     fi
 done
 
-for u in ${UNITS[@]}; do
-    for a in ${ACTION[@]}; do
-        if ! $CMD $a $u; then
-            #systemctl status doesn't play nice so this is disabled
-            #echo -e "ERR: command returned error\n\t$ $CMD $a $u"
-            #exit 1 
-            :
-        fi
+if [ ! -z "$TIMERS" ]; then
+    cmd=list-timers
+    if [ -z "$UNITS" ]; then
+        $CMD $cmd --all --no-pager
+        Q=$($CMD $cmd --all --no-legend | grep -o "\w*\.timer")
+        UNITS+=( $Q )
+    else
+        U=()
+        for u in ${UNITS[@]}; do
+            $CMD $cmd --all --no-pager --no-legend | grep "$u" 
+            Q=$($CMD $cmd --all --no-legend | grep -o "\w*\.timer" | grep "$u")
+            U+=( $Q )
+        done
+        UNITS=( "${U[@]}" )
+    fi
+fi
+
+if [ ! -z "${ACTION[*]}" ]; then 
+if [ ! ${#UNITS[@]} -gt 1 ] || \
+   [ "${ACTION[*]}" == "status" ] || \
+   yesno -N "${ACTION[*]} ${#UNITS[@]} units?"
+then 
+    for u in ${UNITS[@]}; do
+        for a in ${ACTION[@]}; do
+            echo ">>> $CMD $a $u"
+            if ! $CMD $a $u; then
+                #systemctl status doesn't play nice so this is disabled
+                #echo -e "ERR: command returned error\n\t$ $CMD $a $u"
+                #exit 1 
+                :
+            fi
+        done
     done
-done
+fi
+fi
+
+if [ ! -z "$LOG" ]; then 
+    ARGS=" $LOGTAIL $LOGBOOTS "
+    if [ ! -z "$USERMODE" ]; then
+        ARGS="--user $ARGS"
+    fi
+    if [ ! -z "$LOGSINCE" ]; then
+        ARGS="$ARGS -S $LOGSINCE"
+    else
+        ARGS="$ARGS -e"
+    fi
+    if [ -z "$UNITS" ]; then 
+        ARGS="-p 5 $ARGS"
+    else
+        ARGS="-p 6 $ARGS"
+        for u in ${UNITS[@]}; do
+            ARGS="$ARGS -u $u"
+        done
+    fi
+    if [ ! -z "$LOGLEVEL" ]; then
+        ARGS="$ARGS -p $LOGLEVEL"
+    fi
+    eval journalctl $ARGS
+fi
